apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-mlops-group-8-fastapi-lungs
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-mlops-group-8-fastapi-lungs
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.deployment.containerPort }}
            name: {{ .Values.deployment.portName }}
            protocol: {{ .Values.deployment.protocol }}
      nodeName: {{ .Values.nodeName }}
      restartPolicy: Always