# Declare variables to be passed into your templates.
name: fastapi-lungs
replicaCount: 1
namespace: mlops-group-8
nodeName: carlier-alex

image:
  repository: ghcr.io/willemsbrecht/lungsfastapi
  tag: '1.0.0'
  pullPolicy: Always

deployment:
  portName: 80tcp
  serviceType: ClusterIP
  protocol: TCP
  containerPort: 80

service:
  name: fastapi-lungs-svc
  portName: 80tcp-svc
  type: ClusterIP
  port: 80
  targetPort: 80
  protocol: TCP

nodeSelector: 
  kubernetes.io/hostname: carlier-alex

