# This is a basic workflow to help you get started with Actions

name: mlops_runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Train_and_register_AI_model:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Azure login"  
        uses: azure/login@v1
        with: # Set Azure credentials secret as an input
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run data prep script'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          python3 steps/01_DataPreparing.py
          
      - name: 'Run Training script'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          python3  steps/02_Training.py
          
      - name: 'Register model'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          python3  steps/03_RegisterModel.py
          
  Build_Fast_API_image:
    # needs will wait until the specified jobs has succeeded
    needs: Train_and_register_AI_model
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
          
      - name: 'Deploy model'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          python3 steps/04_DeployModel.py
      
      - name: "Save config data"
        uses: actions/upload-artifact@v2.2.3
        with:
          name: config-data
          path: tmp
          retention-days: 10
          
      - name: Create the needed directories for the fast-api image
        working-directory: api/api/app
        run: |
          mkdir images

      - name: Set PAT secret
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io --username WillemsBrecht --password-stdin

      - name: Build Dockerfile and push to github
        working-directory: api/api
        run: |
          docker build -t ghcr.io/willemsbrecht/lungsfastapi .
          docker push ghcr.io/willemsbrecht/lungsfastapi
          
  Deploy_to_cluster:
    needs: Build_Fast_API_image
    runs-on: self-hosted
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update kubernetes deployments
        working-directory: charts
        run: |
          helm upgrade --install fastapi-lungs -n mlops-group-8 ./fastapi-lungs
          kubectl port-forward service/fastapi-lungs-svc 8701:80 -n mlops-group-8 &
        #probeer echo PODNAME
        #export POD_NAME=$(kubectl get pods --namespace mlops-group-8 -l "app.kubernetes.io/name=fastapi-lungs,app.kubernetes.io/instance=fastapi-lungs" -o jsonpath="{.items[***].metadata.name}")
        #kubectl port-forward $POD_NAME 8701:80 --namespace mlops-group-8

